name: jobstash_bot
description: A sample command-line application.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.1.3

dependencies:

  # Dependency injection
  riverpod: ^2.4.9

  # Networking
  functions_framework: ^0.4.0
  shelf: ^1.0.0

  # App packages
  jobstash_api:
    path: ./packages/jobstash_api
  database:
    path: ./packages/database

  # Telegram
  chatterbox: ^1.3.0

  # utils
  logger: ^2.0.2+1
  collection: ^1.18.0
  dotenv: ^4.2.0

dev_dependencies:
  # Code generation
  build_runner: ^2.0.0
  functions_framework_builder: ^0.4.0

  # Linting
  lints: ^2.0.0

  # Testing
  test: ^1.21.0

