name: ai_assistant
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.1.3

dependencies:

  # AI
  openai_api: ^0.3.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
